apiVersion: apps/v1
kind: Deployment #Tipo do recurso, aqui é um Deployment que gerencia a criação e atualização dos Pods.
metadata:
  name: tc-fast-food-app
  namespace: namespace-tc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc-fast-food-app
  template:
    metadata:
      labels:
        app: tc-fast-food-app
    spec:
      containers:
        - name: tc-fast-food-app
          image: lfmelo/tc-fast-food:tagname   # <== Substitua pelo seu usuário e tag do Docker Hub!
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/fast-food?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          livenessProbe: # Detecta se o app está saudável (senão, reinicia o container).
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30  # Tempo para o app subir antes de começar o check
            periodSeconds: 10         # Verifica a cada 10 segundos
            failureThreshold: 3       # Se falhar 3 vezes seguidas, reinicia
          readinessProbe: # Detecta se o app está pronto para receber tráfego (senão, remove do Service temporariamente).
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10  # Começa a checar se está pronto após 10s
            periodSeconds: 5         # Verifica a cada 5 segundos
            failureThreshold: 2      # Se falhar 2 vezes, remove do load balancer
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"