apiVersion: v1
kind: Service
metadata:
  name: tc-fast-food-service
  namespace: namespace-tc
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    app: tc-fast-food-app
